### PR TITLE
Proposed update to support dnspython version 2.0

### PR DESCRIPTION
**Pull request by JasonCoombs**
Not meant to be a comprehensive update. This edit has been unit tested only once, and not exhaustively. At first glance this appears to work.

See also: https://github.com/rthalley/dnspython/pull/473#issuecomment-682190562

### CODE REVIEW

**Comment by JasonCoombs** [comment]
```
$ doh bitcoin.sucks BLAH @dns.google
Traceback (most recent call last):
  File "/usr/local/bin/doh", line 85, in main
    if dns.rdatatype.from_text(arg.upper()):
  File "/usr/local/lib/python3.8/site-packages/dns/rdatatype.py", line 147, in from_text
    return RdataType.from_text(text)
  File "/usr/local/lib/python3.8/site-packages/dns/enum.py", line 43, in from_text
    raise cls._unknown_exception_class()
dns.rdatatype.UnknownRdatatype: DNS resource record type is unknown.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/doh", line 136, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/doh", line 90, in main
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.
```

FYI raising a SyntaxError might not be the ideal response, but that is what this simple PR gives us and it is as-intended.

**Comment by JasonCoombs** [comment]
valid RdataTypes are in the `class RdataType` enum:

https://dnspython.readthedocs.io/en/stable/_modules/dns/rdatatype.html#RdataType

```
$ doh bitcoin.sucks CNAME @dns.google
; <<>> DoH Client 0.1 <<>> bitcoin.sucks CNAME @dns.google
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7718
;; flags: QR RD RA

;; QUESTION:
bitcoin.sucks. IN CNAME

;; ANSWER:

;; AUTHORITY:
. 1799 IN SOA ns1.everything.sucks. noc.everything.sucks. 2008121302 10800 3600 700000 86400

;; Server: https://dns.google
;; Query time: 423 msec
```

**Comment by aramg** [comment]
Thanks.

IMO the current flow to just print "Invalid arg" is better UX rather than it looking like the program crashed.

**Comment by aramg** [comment]
in master

**Pull request closed without merging**
